### ISSUE TITLE
UID Question

### ISSUE THREAD

**Issue by rlee1990** [AgoraIO-Community/Flutter-UIKit#10]
Are we able to use string uids or how can we use agora user accounts with this package?

**Comment by Meherdeep** [comment]
@rlee1990 String uid is not supported in this release. We will try to add it in our upcoming releases.

**Comment by rlee1990** [comment]
@rlee1990 thanks that would be a big help as I don't see how it's scalable to create a token for millions of users with a small combination of numbers.

**Comment by tadaspetra** [comment]
> @rlee1990 thanks that would be a big help as I don't see how it's scalable to create a token for millions of users with a small combination of numbers.

After talking to the team, it seems that stringUid is actually not recommended to use.

And it actually is scalable to millions of users with int. An int can support 2^63 uids. And the SDK supports minimum 2^31 uids, which is 2.1 Billion. So there isn't really any scalability issues with numbers.

**Comment by rlee1990** [comment]
Thanks for that update.

**Comment by tadaspetra** [comment]
No problem! Thanks for pointing it out, and I learned something from this!
