### ISSUE TITLE
Allow Tokens To Be Passed

### ISSUE THREAD

**Issue by rlee1990** [AgoraIO-Community/Flutter-UIKit#11]
It would be useful to allow us to also just provide a token and not just a temp token or a token url as we are creating our tokens using accounts for string uids and so I get the token before calling the uikit functions but I can't pass it to uikit I receive an error for temptoken.

**Comment by rlee1990** [comment]
@Meherdeep any way to allow this? Or am I doing something wrong?

**Comment by Meherdeep** [comment]
@rlee1990 How are you generating your token?

**Comment by rlee1990** [comment]
This is my token code:
I am using a firebase function. I can confirm a token is then created.
```
const channelId = data.channelId;
    const uid = data.uid;
    const isPublisher = data.isPublisher;

    const token = RtcTokenBuilder.buildTokenWithAccount(AGORA_APP_ID, AGORA_Cert, channelId, uid, isPublisher ? RtcRole.PUBLISHER : RtcRole.SUBSCRIBER, privilegeExpiredTs);
    return {'token': token};
```

**Comment by Meherdeep** [comment]
What error are you getting when you pass this token value to the tempToken parameter?

**Comment by rlee1990** [comment]
Here is the error:
`I/flutter (30663): onError: ErrorCode.InvalidToken`
and the token: `006c1cc6f30444b4f628686efa644547e6eIAA5xEJgq23CIWylNCxs6X/m0cXu9iuh7ptIEXHaoWYrp6mNqbngNHC4IgBG8Wc8Oh7fYAQAAQDK2t1gAgDK2t1gAwDK2t1gBADK2t1g`

@Meherdeep

**Comment by rlee1990** [comment]
If I use this temp token that I generated from the site it works:
`006c1cc6f30444b4f628686efa644547e6eIADA/q8OQEAzczW2w9TsLkEOjA03nn7sYYGBmjQMWCi9HqmNqbkAAAAAEACqPfBqTCHfYAEAAQBLId9g`

**Comment by Meherdeep** [comment]
@rlee1990 Are you generating this using String uid?

**Comment by rlee1990** [comment]
Yes I am @Meherdeep could that be the issue?

**Comment by Meherdeep** [comment]
Yes, because the join channel function is using int uid for now. You can fork the repo and change the code accordingly.

**Comment by rlee1990** [comment]
Thanks will do.

**Comment by rlee1990** [comment]
@Meherdeep My fork worked I only added an option for the string uid and still keep everything else if you want to use that when your looking to add it in.

**Comment by holy-dev** [comment]
what should be the url in the tokenUrl: ""?

I'm using node to generate token, to generate token the URL goes something like this: site.com/generate_token?channel=test&uid=120&role=subscriber

**Comment by holy-dev** [comment]
@maxxfrazer  thanks, I solved it. The url format is hardcoded in the plugin.
