### ISSUE TITLE
[PROPOSAL] Refactor getters to functions

### ISSUE THREAD

**Issue by Ascenio** [AgoraIO-Community/Flutter-UIKit#12]
There are these two cases in [AgoraClient](https://pub.dev/documentation/agora_uikit/latest/agora_uikit/AgoraClient-class.html) that getters are used to get async information.

https://github.com/AgoraIO-Community/Flutter-UIKit/blob/4ab388978f322caf99234420f5e8f510ebcd0a34/lib/src/agora_client.dart#L15-L30

This is often thought as not good practice because it tricks the client into thinking that it's a cached or O(1) operation. This is not recommended by [Flutter guideline](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#getters-feel-faster-than-methods).

So maybe it should be changed to a function to make its computation more explicit.

**Comment by tadaspetra** [comment]
Changes merged in #16
