### ISSUE TITLE
[PROPOSAL] Make void functions return Future

### ISSUE THREAD

**Issue by Ascenio** [AgoraIO-Community/Flutter-UIKit#14]
There are some functions, mainly in `SessionController` where it returns void but is actually async, which means the client won't wait for operations. In the `AgoraClient`'s `_initAgoraRtcEngine()` it doesn't catches errors because of this.

**Comment by Meherdeep** [comment]
Thanks @Ascenio for all your suggestion. We will look into it. 

Feel free to create a PR for the same if you want.

**Comment by tadaspetra** [comment]
Changes merged in #15
