### ISSUE TITLE
[BUG] Error: The argument type 'AreaCode' can't be assigned to the parameter type 'List<AreaCode>?'.  - 'AreaCode' is from

### ISSUE THREAD

**Issue by qcks** [AgoraIO-Community/Flutter-UIKit#26]
lib/controllers/session_controller.dart:41:43
```
 void initializeEngine(
      {required AgoraConnectionData agoraConnectionData}) async {
    value = value.copyWith(
      engine: await RtcEngine.createWithConfig(
        RtcEngineConfig(agoraConnectionData.appId,
            areaCode: agoraConnectionData.areaCode),
      ),
      connectionData: agoraConnectionData,
    );
  }
```

**Comment by mrtordoide** [comment]
Also facing this same issue:

`../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_uikit-0.0.2/lib/controllers/session_controller.dart:41:43: Error: The argument type 'AreaCode' can't be assigned to the parameter type 'List<AreaCode>?'.
 - 'AreaCode' is from 'package:agora_rtc_engine/src/enums.dart' ('../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.0.5/lib/src/enums.dart').
 - 'List' is from 'dart:core'.                                          
            areaCode: agoraConnectionData.areaCode), `

**Comment by mrtordoide** [comment]
Also facing this same issue. My error output is given below:

```
../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_uikit-0.0.2/lib/controllers/session_controller.dart:41:43: Error: The argument type 'AreaCode' can't be assigned to the parameter type 'List<AreaCode>?'.
 - 'AreaCode' is from 'package:agora_rtc_engine/src/enums.dart' ('../../../Developer/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.0.5/lib/src/enums.dart').
 - 'List' is from 'dart:core'.                                          
            areaCode: agoraConnectionData.areaCode), 
```

**Comment by Meherdeep** [comment]
@qcks @mrtordoide Fix for this has been added to the dev branch, please have a look at it.

**Comment by mrtordoide** [comment]
Got it working. Thanks @Meherdeep
