### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Basemshawwa** [AgoraIO-Community/Flutter-UIKit#31]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/agora_uikit-0.0.2/lib/controllers/session_controller.dart:41:43: Error: The argument type 'AreaCode' can't be assigned to the parameter type 'List<AreaCode>?'.
 - 'AreaCode' is from 'package:agora_rtc_engine/src/enums.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-4.0.6/lib/src/enums.dart').
 - 'List' is from 'dart:core'.
            areaCode: agoraConnectionData.areaCode),
                                          ^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1035

**Comment by Meherdeep** [comment]
@Basemshawwa Please try using the dev branch.

**Comment by Basemshawwa** [comment]
ok thank you
