### ISSUE TITLE
[BUG][iOS] App Crashed after launching on iphone 12

### ISSUE THREAD

**Issue by luvishq** [AgoraIO-Community/Flutter-UIKit#34]
**Describe the bug**
On Android the worked fine, but on iPhone 12 it crashed with the below exception:

```
flutter: onJoinChannel: agora_test_poc, uid: 1221795414
flutter: userJoined: 4183955454
flutter: Remote audio state changed for 4183955454, state: AudioRemoteState.Starting and reason: AudioRemoteStateReason.Internal
-[__NSDictionaryM longLongValue]: unrecognized selector sent to instance 0x2801f2f20
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSDictionaryM longLongValue]: unrecognized selector sent to instance 0x2801f2f20'
*** First throw call stack:
(0x18bf2e708 0x1a0a387a8 0x18be31bfc 0x18bf31260 0x18bf33560 0x10d1d9bb8 0x10d1d5400 0x10d4eaa60 0x10d1fbd7c 0x10d505070 0x10d49f1d4 0x10d4a19fc 0x18bea91d4 0x18bea8dd0 0x18bea8220 0x18bea1fd4 0x18bea1308 0x1a3524734 0x18e91f75c 0x18e924fcc 0x1005b2418 0x18bb5dcf8)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001ba233334 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1ba233334 <+8>:  b.lo   0x1ba233354               ; <+40>
    0x1ba233338 <+12>: pacibsp
    0x1ba23333c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1ba233340 <+20>: mov    x29, sp
```

**To Reproduce**
1.  Launch the app on real iphone device
2. The app crashed after the user joins the channel

**Expected behavior**
Shouldn't crash

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 14.5

I also don't see the video being rendered.

**Comment by luvishq** [comment]
@Meherdeep : Getting a similar exception on the test app as well.

**Comment by luvishq** [comment]
@Meherdeep : here's the code repo where it is crashing for us on ios : https://github.com/luvishq/agora_poc

**Comment by luvishq** [comment]
Can you point out what's wrong with it ?

**Comment by Meherdeep** [comment]
Hey @luvishq, I tried building your app with the credentials you provided and it was missing the token because of which it was throwing an error. I tried building the same app with my credentials and it worked fine. 

Can you try generating a temp token from your console and use it in the `AgoraConnectionData` function?

**Comment by luvishq** [comment]
Hey @Meherdeep , 

Sure here's the  temp token : 00655285ac327784e0aa74269eba5b7ff20IABcF/WP59Flv7XNB+4tjYqK05X/fdaE5hg6Xgfsk0RD7VrHnl0AAAAAEABQGUv2XVgMYQEAAQBdWAxh

Just wanted to confirm that you tested on a real phone right ? for me it's crashing ios 14.5.

**Comment by Meherdeep** [comment]
@luvishq Yes, I built it on a physical device running iOS 14.6 and it works perfectly. I tried closing the video window by pressing the disconnect button (I guess that's what you meant by closing the video window) and that brings me to an empty screen. 

I wasn't able to reproduce the crash message that you shared. Can you try adding breakpoints in your code to possibly see where the code is failing?

**Comment by luvishq** [comment]
hey @Meherdeep , i fixed this issue, something related to ios configuration on our end. It's working great. Thank you so much for being patiently helping us :)

**Comment by yhfy2006** [comment]
> hey @Meherdeep , i fixed this issue, something related to ios configuration on our end. It's working great. Thank you so much for being patiently helping us :)

Do you remember what ios config was related to this please?
