### ISSUE TITLE
[FEATURE] Have an option to keep the aspect ratio of remote video?

### ISSUE THREAD

**Issue by mrtordoide** [AgoraIO-Community/Flutter-UIKit#36]
**Is your feature request related to a problem? Please describe.**
It is not an issue but something I think will be very useful for cross platform view.

**Describe the solution you'd like**
I am looking forward to keep the width and height aspect ratio of each of the remote streams captured by the sdk selects rather than having an expanded view of the remote video which looks too zoomed in and with the probabilities of having UIKit in flutter web, it looks like an important feature to have.

**Describe alternatives you've considered**
I made use of `videoSizeChanged` and `remoteVideoStateChanged` callbacks and was able to work this out in iOS and Android platforms with `agora_rtc_engine` using `FittedBox` and `AspectRatio` widgets. However, web version of `agora_rtc_engine` (which i understand is not released yet) did not support the call backs so not sure how this can work in web at the moment.

**Additional context**
This will be very helpful specially when we have a screenshare in the channel as the aspect ratio of the shared content/screen will be maintained rather than being zoomed in.

**Comment by Meherdeep** [comment]
Hey @mrtordoide, Would you prefer a solution where we can offer a method to set your own `VideoRenderMode` in a `SurfaceView`? 
https://pub.dev/documentation/agora_rtc_engine/latest/agora_rtc_engine/VideoRenderMode-class.html

**Comment by mrtordoide** [comment]
Yes, that will be great @Meherdeep. Thank you! But I reckon it will only work on mobile platforms right? Do you know if web implementation at `dev/flutter2` support `VideoRenderMode` currently? I was unable to make it work.

**Comment by Meherdeep** [comment]
@mrtordoide `VideoRenderMode` is a property of the `SurfaceView` and is available for web as well. If you want to try it out you can fork the web branch and add a VideoRenderMode

**Comment by mrtordoide** [comment]
@Meherdeep Thanks for your response. Could you please tell me where SurfaceView is used when I use Flutter UIKit? Isn't it only `AgoraVideoViewer()` widget that is required instead of `SurfaceView` widget?

**Comment by Meherdeep** [comment]
@mrtordoide You're correct. `AgoraVideoViewer` uses `SurfaceView` internally. If you want to add render mode then you will have to fork the repo and add `VideoRenderMode` over here: https://github.com/AgoraIO-Community/Flutter-UIKit/blob/main/lib/src/layout/grid_layout.dart#L32
