### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by karzhartz** [AgoraIO-Community/Flutter-UIKit#37]
When i start a live stream it just shows a black screen
This is what it logs out in the terminal

E/libc    ( 5577): Access denied finding property "net.dns1"
E/libc    ( 5577): Access denied finding property "net.dns2"
E/libc    ( 5577): Access denied finding property "net.dns3"
E/libc    ( 5577): Access denied finding property "net.dns4"
W/System.err( 5577): java.io.FileNotFoundException: /sys/class/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err( 5577):    at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err( 5577):    at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err( 5577):    at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err( 5577):    at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err( 5577): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err( 5577):    at libcore.io.Linux.open(Native Method)
W/System.err( 5577):    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err( 5577):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err( 5577):    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err( 5577):    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
W/System.err( 5577):    at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err( 5577):    ... 3 more
W/System.err( 5577): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err( 5577):    at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err( 5577):    at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err( 5577):    at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err( 5577):    at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err( 5577): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err( 5577):    at libcore.io.Linux.open(Native Method)
W/System.err( 5577):    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err( 5577):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err( 5577):    at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err( 5577):    at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
W/System.err( 5577):    at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err( 5577):    ... 3 more
W/GENP.0  ( 5577): type=1400 audit(0.0:3553): avc: denied { read } for name="temp" dev="sysfs" ino=18011 scontext=u:r:untrusted_app_29:s0:c153,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0 app="applicationId"
W/GENP.0  ( 5577): type=1400 audit(0.0:3554): avc: denied { read } for name="temp" dev="sysfs" ino=18011 scontext=u:r:untrusted_app_29:s0:c153,c256,c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0 app="applicationId"

**Comment by maxxfrazer** [comment]
did you set the application ID and a valid access token? (temporary tokens are valid for 24 hours)
