### ISSUE TITLE
[BUG] Issue with firebase firestore

### ISSUE THREAD

**Issue by holy-dev** [AgoraIO-Community/Flutter-UIKit#44]
**Describe the bug**
It's shifting build directory inside android/app/ and Firestore not working in release. After remove agora, Firestore starts working normally and build directory is also in normal place.

**To Reproduce**
Just simple single line firestore operation.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur 11.0

**Smartphone (please complete the following information):**
 - Device: Tried on android 11, real device & emulator

**Comment by tadaspetra** [comment]
Sorry for the late reply. Can you describe what you mean by shifting build directory? And can you send the logs as well

**Comment by holy-dev** [comment]
Normally the build directory is /build but after adding the package the build directory going inside /android/app

There's nothing unnecessary in the log.

**Comment by Meherdeep** [comment]
@holy-dev Can you please confirm if this occurs with iOS as well? And, for Android, you can try changing your project directory inside `build.gradle`

**Comment by Meherdeep** [comment]
@holy-dev Closing this issue for now. Feel free to open it again if you're still facing this issue.
