### ISSUE TITLE
[FEATURE] Add pictures on the readme about the package.

### ISSUE THREAD

**Issue by IsmailAlamKhan** [AgoraIO-Community/Flutter-UIKit#5]
Before using a package most of us see the images to see the package in action. So we would like pictures on the readme from the package.

**Comment by Meherdeep** [comment]
@IsmailAlamKhan Thanks for your suggestion, we will make sure to add them in the next release.

**Comment by maxxfrazer** [comment]
@IsmailAlamKhan in the meantime, there are pictures in the wiki pages:
https://github.com/AgoraIO-Community/Flutter-UIKit/wiki

**Comment by IsmailAlamKhan** [comment]
thank you so much guys, sorry for the delay was busy. @maxxfrazer @Meherdeep
