### ISSUE TITLE
[BUG] Black screen on Android Device

### ISSUE THREAD

**Issue by hori20N** [AgoraIO-Community/Flutter-UIKit#53]
**Describe the bug**
When I create a new SurfaceView or refresh its layout, there is a black frame before video stream loaded （It only occurs on android device)

**To Reproduce**
1. just create a new SurfaceView
2. switch layout type

**Expected behavior**
no black screen

**Screenshots**
1.
![1](https://user-images.githubusercontent.com/4444837/138815180-e21108fb-215f-4103-8909-3421c08ae5a1.jpg)
2.
![2](https://user-images.githubusercontent.com/4444837/138815203-a99f186b-acd9-4b8e-bdbc-e34546e03c5e.jpg)
3.
![3](https://user-images.githubusercontent.com/4444837/138815238-495e20f2-fa25-450f-9470-e250d876c5bb.jpg)
4.
![4](https://user-images.githubusercontent.com/4444837/138815267-af7c0888-63e4-4238-9d35-fcfd56f0ce27.jpg)
5.
![5](https://user-images.githubusercontent.com/4444837/138815293-3bc23d9d-7033-4621-8a1c-e306322e1368.jpg)

**Comment by tadaspetra** [comment]
Could you share the logs, and some of the code of how you initialized Agora?

**Comment by Meherdeep** [comment]
@hori20N Closing this issue for now. Feel free to open it again if you're still facing this issue.
