### ISSUE TITLE
[BUG] onError: ErrorCode.JoinChannelRejected

### ISSUE THREAD

**Issue by moesaid** [AgoraIO-Community/Flutter-UIKit#56]
**Describe the bug**
getting error on joining a room 

```
Local video state changed state: LocalVideoStreamState.Failed and error: LocalVideoStreamError.DeviceNotFound
onError: ErrorCode.JoinChannelRejected
```

**To Reproduce**
once on 

**Expected behavior**
- so once joining a room on a video call I get the error 
- if joining on a real device I get the error but I join the call 
- using IOS simulator I get the error with joining the call

**Screenshots**

![image](https://i.imgur.com/oCvgTlY.png)
![Imgur](https://i.imgur.com/At42Efa.png)
![Imgur](https://i.imgur.com/mL2vm9W.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Iphone 8+ 
 - Device: simulator 13
 - Os: 15

**Comment by tadaspetra** [comment]
First thing I would check is that the tempToken isn't expired. It expires every 24 hours. Was this working before, or has it never worked?

**Comment by moesaid** [comment]
Hi Tadas! love your videos buddy!
actually never worked tried multiple times regenerating tempToken on Agora console, and experienced the same error.

**Comment by tadaspetra** [comment]
Thank you so much! That really means a lot :)

But can you try to run the example app that we have in the repo, and see if that works. I am wondering whether this could be something to do with GetX initialization. According to the documentation, these are some possible reasons for that error, but  from what you shared those aren't likely. One of my guesses is that GetX doesn't initialize it appropriately. If you try with the basic example app would be great

<img width="865" alt="Screen Shot 2021-12-07 at 2 24 27 PM" src="https://user-images.githubusercontent.com/60107328/145115334-61693819-6178-4407-905d-a226b8fa1f2d.png">

**Comment by moesaid** [comment]
I didn't have a chance to run the example, but for sure will do so this week. I will let you know :)

**Comment by moesaid** [comment]
running the example 

```
flutter: Error occured while initializing Agora RtcEngine: PlatformException(7, not initialized, null, null)
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
#0      SessionController.joinVideoChannel
package:agora_uikit/controllers/session_controller.dart:397
<asynchronous suspension>
#1      AgoraClient.initialize
package:agora_uikit/src/agora_client.dart:69
<asynchronous suspension>
#2      _MyAppState.initAgora
package:agora_uikit_example/main.dart:32
<asynchronous suspension>

```

**Comment by Meherdeep** [comment]
@moesaid Closing this issue for now. Feel free to open it again if you're still facing this issue.
