### ISSUE TITLE
Live Stream Issue

### ISSUE THREAD

**Issue by rlee1990** [AgoraIO-Community/Flutter-UIKit#60]
**Describe the bug**
When an audience member joins a live stream as an audience member their view is split with a blank top half even though there is only 1 person broadcasting.

**To Reproduce**
Create a live stream as a broadcaster and have someone view it as an audience member.

**Expected behavior**
Should just show the broadcaster taking the whole view.

**Smartphone (please complete the following information):**
 - Device: iPhone 8, Samsung Galaxy Note 8, and Samsung Galaxy Fold 3
 - OS: ios 15

**Comment by rlee1990** [comment]
Here is a photo of what I am referring to ![image](https://user-images.githubusercontent.com/21372502/146957326-518e0bce-13d7-43b8-8872-7c0ae8121ad0.jpeg) @Meherdeep @tadaspetra

**Comment by rlee1990** [comment]
I found that the issue might be with the layout _getRenderViews() function for broadcast calling the 
```
for (AgoraUser user in widget.client.sessionController.value.users) {
      user.videoDisabled
          ? list.add(
              DisabledVideoStfWidget(
                disabledVideoWidget: widget.disabledVideoWidget,
              ),
            )
          : list.add(
              rtc_remote_view.SurfaceView(
                channelId: widget
                    .client.sessionController.value.connectionData!.channelName,
                uid: user.uid,
                renderMode: widget.videoRenderMode,
              ),
            );
    }
```

**Comment by rlee1990** [comment]
@tadaspetra @Meherdeep it seams that when doing Livestreams the audience view is being added as a second view

**Comment by rlee1990** [comment]
I found changing the code to this fixed the issue:
```
if (widget.client.sessionController.value.clientRole !=
        ClientRole.Audience) {
      widget.client.sessionController.value.isLocalVideoDisabled
          ? list.add(
              DisabledVideoStfWidget(
                disabledVideoWidget: widget.disabledVideoWidget,
              ),
            )
          : list.add(
              rtc_local_view.SurfaceView(
                zOrderMediaOverlay: true,
                renderMode: widget.videoRenderMode,
              ),
            );
    }
```

**Comment by Meherdeep** [comment]
@rlee1990 Thanks for flagging this. We will update this in our next release or you can submit a PR for the same.

**Comment by maxxfrazer** [comment]
Looks like this one is fixed now, closing issue.
