### ISSUE TITLE
Error occured while initializing Agora RtcEngine: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)

### ISSUE THREAD

**Issue by shanbit200** [AgoraIO-Community/Flutter-UIKit#61]
Error occured while initializing Agora RtcEngine: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)

for Mac Desktop development

<img width="806" alt="Screenshot 2021-12-22 at 12 19 58 PM" src="https://user-images.githubusercontent.com/4158103/147048389-1f345f45-74b7-44a6-bad4-be9f450c92fa.png">

**Comment by Meherdeep** [comment]
@shanbit200 Agora UIKit currently supports Android and iOS. Desktop support will soon be added in the coming release.
