### ISSUE TITLE
Issue while integrating agora_uikit  in flutter 2.8

### ISSUE THREAD

**Issue by alibharmal110** [AgoraIO-Community/Flutter-UIKit#62]
Getting error while running the video conferencing app , 

Error:

W/System.err(13657): java.io.FileNotFoundException: /sys/class/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(13657): 	at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err(13657): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err(13657): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(13657): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(13657): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(13657): 	at libcore.io.Linux.open(Native Method)
W/System.err(13657): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(13657): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err(13657): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(13657): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
W/System.err(13657): 	at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err(13657): 	... 3 more
W/System.err(13657): java.io.FileNotFoundException: /sys/devices/virtual/thermal/thermal_zone0/temp: open failed: EACCES (Permission denied)
W/System.err(13657): 	at libcore.io.IoBridge.open(IoBridge.java:492)
W/System.err(13657): 	at java.io.FileInputStream.<init>(FileInputStream.java:160)
W/System.err(13657): 	at io.agora.rtc.gdp.GDPAndroid.readOneLine(GDPAndroid.java:383)
W/System.err(13657): 	at io.agora.rtc.gdp.GDPAndroid.getCpuTemperature(GDPAndroid.java:362)
W/System.err(13657): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
W/System.err(13657): 	at libcore.io.Linux.open(Native Method)
W/System.err(13657): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(13657): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
W/System.err(13657): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
W/System.err(13657): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
W/System.err(13657): 	at libcore.io.IoBridge.open(IoBridge.java:478)
W/System.err(13657): 	... 3 more 

Can u help me ! 

android/build.gradle : 

![Screenshot from 2021-12-27 15-27-18](https://user-images.githubusercontent.com/96720958/147460191-3ef560ef-510f-422d-9b09-c24c6f587b2c.png)

AndroidManifest.xml : 

![Screenshot from 2021-12-27 15-26-39](https://user-images.githubusercontent.com/96720958/147460309-f5cfa8c2-11fd-49c8-b10c-33d3197280a8.png)

Video conferencing Page :

![Screenshot from 2021-12-27 15-27-06](https://user-images.githubusercontent.com/96720958/147460259-457533f6-f54e-47fc-8dd7-a779d7ccc45b.png)

**Comment by tadaspetra** [comment]
<img width="547" alt="Screen Shot 2022-01-05 at 2 01 59 PM" src="https://user-images.githubusercontent.com/60107328/148281371-4a6f5dcb-7d29-4166-8be7-8954a7415470.png">

Try updating compileSdkVersion and targetSdkVersion to 31

**Comment by Meherdeep** [comment]
Closing this for now. If you're still facing the issue feel free to reopen it.
