### ISSUE TITLE
Video View showing side blackscreen 

### ISSUE THREAD

**Issue by shamsher400** [AgoraIO-Community/Flutter-UIKit#64]
Hi thanks for giving adorable Agora Video Call UI.
I am faceing issues Video works properly but its showing bothe side black screen. 
if feture alerady implement to working aspect to fit please let me know . thanks in advance

**Comment by Meherdeep** [comment]
Hey @shamsher400, 

Thanks for using the UIKit. I am glad that you liked it. 
The UIKit has `VideoRenderMode` which can help you adjust the video size and fit. You can do this by simply calling the `videoRenderMode` inside your `AgoraVideoViewer` class. 
To fill the entire space, you can try this:

```dart
AgoraVideoViewer(
    client: client,
    videoRenderMode: VideoRenderMode.Hidden
), 
```

You can refer to this doc to know more about `VideoRenderMode`: https://docs.agora.io/en/Video/API%20Reference/flutter/v4.0.5/agora_rtc_engine/VideoRenderMode-class.html

**Comment by shamsher400** [comment]
Thanks @Meherdeep you made my day
