### ISSUE TITLE
[BUG]  set BeautyEffectOptions not working

### ISSUE THREAD

**Issue by Hawaii88** [AgoraIO-Community/Flutter-UIKit#67]
Set up Beauty Effect Options not working

I use agora_rtc_engine: ^4.0.7 to set with flutter. already adjust following the document but still not working.

To Reproduce
_engine.setBeautyEffectOptions(
true,
BeautyOptions(
lighteningContrastLevel: LighteningContrastLevel
lighteningLevel: value / 10,
rednessLevel: value / 10,
smoothnessLevel: value / 10,
),

Expected behavior
It's suppost to working on frontend.

Screenshots
So i attacted video screenshot to show how I adjust.

Smartphone:

Device: [e.g. iPhone12]
OS: [e.g. iOS15.2.1]
[666045070.413774.mp4.zip](https://github.com/AgoraIO-Community/Flutter-UIKit/files/8030132/666045070.413774.mp4.zip)

**Comment by Meherdeep** [comment]
@Hawaii88 I am not so sure how you're calling the `_engine`. But the correct method to call the `setBeautyEffectOptions` from the UIKit would be :
```dart
client.sessionController.value.engine.setBeautyEffectOptions(enabled, options)
```

**Comment by Meherdeep** [comment]
@Hawaii88 Closing this issue for now. Feel free to open it again if you're still facing this issue.
