### ISSUE TITLE
package dependencies are outdated

### ISSUE THREAD

**Issue by apkpotty** [AgoraIO-Community/Flutter-UIKit#75]
**Describe the bug**
Dependent packages are pinned. eg. agora_rtc_engine is pinned to 4.0.6 and permission_handler 8.0.0+1

**To Reproduce**
1. Go to pubspec.yaml
2. add package dependencies 

agora_uikit: ^0.0.4
agora_rtc_engine: ^5.0.1
permission_handler: ^9.0.2

4. Run flutter pub get
5. Shows the below error

Running "flutter pub get" in xxxxxxxxx ...                 
Because agora_uikit >=0.0.4 depends on agora_rtc_engine ^4.0.6 and xxxxxxxxx depends on agora_rtc_engine ^5.0.1, agora_uikit >=0.0.4 is forbidden.
So, because xxxxxxxxx depends on agora_uikit ^0.0.4, version solving failed

flutter pub get
Running "flutter pub get" in xxxxxxxxx ...                 
Because xxxxxxxxx depends on agora_uikit ^0.0.4 which depends on permission_handler ^8.0.0+1, permission_handler ^8.0.0+1 is required.
So, because xxxxxxxxx depends on permission_handler ^9.2.0, version solving failed.

**Expected behavior**
Expected 'flutter pub get' to complete without error

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Framework: Flutter
 - Version 2.10.4

**Comment by Meherdeep** [comment]
@apkpotty Looks like you're importing the `agora_rtc_engine` and `permission_handler` along with the UIKit, which is already added to the UIKit. 

In case you want to use access any other `agora_rtc_engine` method/callback which is not already added to the UIKit, you can simply call the `agora_rtc_engine` object and call any method using that. Similarly for any kind of permission you can add it to the `enabledPermission` array. 

You can read more about it here in the [Wiki](https://github.com/AgoraIO-Community/Flutter-UIKit/wiki) or refer to this [blog](https://www.agora.io/en/blog/creating-a-flutter-video-streaming-app-with-three-lines-of-code/).

**Comment by Meherdeep** [comment]
@apkpotty The dependencies have been updated to the latest version in our new release [v1.0.0](http://pub.dev/packages/agora_uikit). 


Closing this issue for now, feel free to reopen if the issue still persists.
