### ISSUE TITLE
Unable to end call after a specific duartion

### ISSUE THREAD

**Issue by GitAnubhav1** [AgoraIO-Community/Flutter-UIKit#76]
I am using Flutter-UIKit for my project and I am looking for way that will end the call after a specific duration. Is it possible with UIKit.
My requirement is that a video call can only run for a specific duration and after that it should end automatically. 
Any help in this regard would be really helpful. Thanks

**Comment by Meherdeep** [comment]
Hey @GitAnubhav1, You can try setting a duration for a token. Once the token expires you can refer to the `agora_rtc_engine` object and call the end call method.

**Comment by GitAnubhav1** [comment]
> Hey @GitAnubhav1, You can try setting a duration for a token. Once the token expires you can refer to the `agora_rtc_engine` object and call the end call method.

Thanks a lot
