### ISSUE TITLE
Unable to use it woth latest SDK and latest packages, please fix the issues and support latest packages like build runner v9

### ISSUE THREAD

**Issue by fisforfaheem** [AgoraIO-Community/Flutter-UIKit#79]
I want to use the latest version of agora but this is the problem i cant use it because of this

**Comment by Meherdeep** [comment]
Hope the above solution helped. If the problem still persists you can use the latest version of the UIKit ([v1.0.0](http://pub.dev/packages/agora_uikit)) where we are using the latest version of the Agora SDK

If the problem still persists feel free to reopen the issue.

**Comment by fisforfaheem** [comment]
I hope it keeps updating  Thanks
