### ISSUE TITLE
[FEATURE] Live Streaming Example

### ISSUE THREAD

**Issue by momoleu** [AgoraIO-Community/Flutter-UIKit#8]
Hello, great work! Could we have an example of Live Streaming like Instagram using this package?

**Comment by Meherdeep** [comment]
Hey @momoleu,

To create a live streaming application just add the `agoraChannelData` parameter inside the AgoraClient class. Using that you can specify the channel type (Live streaming or communication) and the client role (broadcaster or audience).

Have a look at this: https://github.com/AgoraIO-Community/Flutter-UIKit/wiki/Examples#adding-video-streaming-to-your-app

**Comment by momoleu** [comment]
Hello @Meherdeep thank you for your help.
