### ISSUE TITLE
[BUG] it wont install the plugin because my  permission_handler is up to date 

### ISSUE THREAD

**Issue by jack84156** [AgoraIO-Community/Flutter-UIKit#80]
Because every version of agora_uikit depends on permission_handler ^8.0.0+1 and my app depends on permission_handler ^9.2.0, agora_uikit is forbidden.
So, because my app depends on agora_uikit ^0.0.4, version solving failed.
pub get failed (1; So, because whosaround depends on agora_uikit ^0.0.4, version solving failed.)

**Comment by Meherdeep** [comment]
Hey @jack84156 , 

You can add all the additional permissions you need in the `enabledPermission` array inside the `AgoraClient` class.

**Comment by Meherdeep** [comment]
Hope the above solution helped. If the problem still persists you can  use the latest version of the UIKit ([v1.0.0](http://pub.dev/packages/agora_uikit)) where we are using the latest version of permission_handler (v9.2.0)

If the problem still persists feel free to reopen the issue.
