### ISSUE TITLE
[BUG] I am not able to find the duration of the call

### ISSUE THREAD

**Issue by GitAnubhav1** [AgoraIO-Community/Flutter-UIKit#81]
Once any user ends the call or decided to opt out of the video call, is there a way we can find the duration of the call?

**Comment by maxxfrazer** [comment]
@GitAnubhav1, you can get the duration for the local user on the device:
https://docs.agora.io/en/Video/API%20Reference/flutter/API/rtc_api_data_type.html?platform=Flutter#class_rtcstats

**Comment by maxxfrazer** [comment]
Looks like @Meherdeep's comment fixes the solution, no response in 7 days so closing. Feel free to open again if this solution did not work for you.
