### ISSUE TITLE
how to send and receive messages in rtm 

### ISSUE THREAD

**Issue by Nader2004** [AgoraIO-Community/Flutter-UIKit#83]
Hello I have been trying to send and receive message through the `AgoraRtmChannel` Object. But whenever i listen to messages through the `onMessageReceived`, it tells me that I called the `onMessageReceived` on null,

Here is the code:

```
` The client is already initialized and I have also provided a username to  use RTM`
_channel = client.sessionController.value.agoraRtmChannel;
_channel.onMessageReceived = (rtmMessage, member) {
      print(rtmMessage.text);
    };
``` 
Here is the error : 

```
The setter 'onMessageReceived=' was called on null.
Receiver: null
Tried calling: onMessageReceived=Closure: (AgoraRtmMessage, AgoraRtmMember) => Null
```

**Comment by Meherdeep** [comment]
Hey @Nader2004 , In your `AgoraConnectionData` class can you try defining `rtmEnabled` as `true`

**Comment by Meherdeep** [comment]
Hey @Nader2004 , Inside your `AgoraClient` you can use `agoraRtmChannelEventHandler` to call any callback from the Agora RTM Channel class.

**Comment by Nader2004** [comment]
Hey @Meherdeep thanks for replying, I have tried looking for a named argument that have to do anything with rtm messages but couldn't find one except two that are about rtm  : 

```
agoraEventHandlers: AgoraEventHandlers(
        rtmpStreamingEvent: ,
        rtmpStreamingStateChanged: ,
     ),
```

Also how can I send messages then using rtm from UIKit.

**Comment by Nader2004** [comment]
Hey @Meherdeep thanks for the package update. But is still actually facing the problem of sending messages, when I call `sendMessage` from `AgoraRtmChannel` like that : `client.sessionController.value.agoraRtmChannel.sendMessage(
                              AgoraRtmMessage.fromText(text));`, it fails with `error code 102`, which according to the agora documentation is about rtm login issue. So is this the right way to send a message or how to resolve that error? Thanks!

**Comment by Nader2004** [comment]
hey @Meherdeep I apologize for the late response, I have added the `if check` but the error still exist. But I did extra observation on the error and discovered that by calling : `client.initialize()` , it doesn't actually call the Rtm login method. 
Here is the code of the `initialize()` method:

```
Future<void> initialize() async {
    if (_initialized) {
      return;
    }

    try {
      await _sessionController.initializeEngine(
          agoraConnectionData: agoraConnectionData);
    } catch (e) {
      log("Error while initializing Agora RTC SDK", level: Level.error.value);
    }

    if (agoraConnectionData.rtmEnabled) {
      try {
        await _sessionController.initializeRtm(
            agoraRtmClientEventHandler ?? AgoraRtmClientEventHandler());
      } catch (e) {
        log("Error while initializing Agora RTM SDK. ${e.toString()}",
            level: Level.error.value);
      }
    }

    if (agoraChannelData?.clientRole == ClientRole.Broadcaster ||
        agoraChannelData?.clientRole == null) {
      await _sessionController.askForUserCameraAndMicPermission();
    }
    if (enabledPermission != null) {
      await enabledPermission!.request();
    }

    _sessionController.createEvents(
      agoraRtmChannelEventHandler ?? AgoraRtmChannelEventHandler(),
      agoraEventHandlers ?? AgoraRtcEventHandlers(),
    );

    if (agoraChannelData != null) {
      _sessionController.setChannelProperties(agoraChannelData!);
    }

    await _sessionController.joinVideoChannel();
    _initialized = true;
  }

```

The important part here is the : 

```
if (agoraConnectionData.rtmEnabled) {
      try {
        await _sessionController.initializeRtm(
            agoraRtmClientEventHandler ?? AgoraRtmClientEventHandler());
      } catch (e) {
        log("Error while initializing Agora RTM SDK. ${e.toString()}",
            level: Level.error.value);
      }
    }
```
When calling `initializeRtm()` only the `RtmClient` is created but there is no callback for the login method:

```
Future<void> initializeRtm(
      AgoraRtmClientEventHandler agoraRtmClientEventHandler) async {
    value = value.copyWith(
      agoraRtmClient: await AgoraRtmClient.createInstance(
        value.connectionData!.appId,
      ),
    );
    if (value.agoraRtmClient != null) {
      addListener(() {
        createRtmClientEvents(agoraRtmClientEventHandler);
      });
    }
  }

```
It's just a speculation, maybe the `login()` method is called elsewhere, I don't know, but the error actually still exists.

**Comment by Meherdeep** [comment]
Hey @Nader2004, the Rtm login occurs once the user joins the RTC channel. Hence, it's called under the `joinChannelSuccess` callback. 
Can you share your code where you're trying to send a message and your `flutter doctor`

**Comment by Meherdeep** [comment]
Hey @Nader2004 Sorry for the late reply. I tried building the sample code that you shared, I just made a small adjustment to the sendMessage logic and I was able to send messages using that. Here's the code for that: 

```
if (client.sessionController.value.isLoggedIn &&
                              client.sessionController.value.isInChannel) {
                            client.sessionController.value.agoraRtmChannel
                                .sendMessage(
                              AgoraRtmMessage.fromText(text),
                            );
                          }
```

**Comment by Meherdeep** [comment]
Closing this issue for now. If you're still facing this issue feel free to reopen it.
