### ISSUE TITLE
InBuiltButton not changing it's state

### ISSUE THREAD

**Issue by abhishekthakur0** [AgoraIO-Community/Flutter-UIKit#86]
If we use inBuiltButton along with the external button in that case InBuiltButtons are not changing its state.
For example mute/unmute does not work .

**To Reproduce**
1. Add few button from inBuiltButton 
2. Add few external button 
3. try to use inBuiltButton

**Comment by Meherdeep** [comment]
Thank you @abhishekthakur0 for flagging this issue. I will fix this with the new release.

**Comment by Meherdeep** [comment]
@abhishekthakur0 The issue has been fixed in the latest version (1.0.2): https://pub.dev/packages/agora_uikit

**Comment by Meherdeep** [comment]
Closing this issue. Feel free to open it again if the solution did not work for you.
