### ISSUE TITLE
SessionController methods deprecation update on the documention

### ISSUE THREAD

**Issue by ndungudedan** [AgoraIO-Community/Flutter-UIKit#88]
After updating to the latest version, methods such as endCall, toggleMute, toggleCamera are no longer defined in the SessionController class.
I am struggling to find documentation on the required migration to implement.
Any assistance will be highly appreciated.

**Comment by Meherdeep** [comment]
All the methods related to in built buttons have been added to the `rtc_buttons.dart`

**Comment by Meherdeep** [comment]
Closing this issue for now. If you're still facing this issue feel free to reopen it.
