### ISSUE TITLE
[FEATURE] is it having incoming video call notification? if not ,any solution for that?

### ISSUE THREAD

**Issue by nowfalsalahudeen** [AgoraIO-Community/Flutter-UIKit#9]

**Comment by Meherdeep** [comment]
Incoming call notification is not included in this SDK. You can use CallKit(iOS) and ConnectionService(Android) to display the call screen. You can read about the complete process [here.](https://docs.agora.io/en/Interactive%20Broadcast/faq/call_invite_notification)
