### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JoshJuncker** [AgoraIO-Community/Flutter-UIKit#96]
**Describe the bug**
When I join a Live Broadcast channel, `AgoraVideoViewer` with channel data `ChannelProfile.LiveBroadcasting` and `ClientRole.Audience` it still splits the screen as if I were going to publish my local feed. On Android, it also turns on my microphone (although not camera) as if I were going to record and publish my local feed. iOS has the same issue, but doesn't turn on microphone recording.  Below is a screenshot of Android showing the half screen as well as the green dot indicating recording. Note that the video in the bottom of the image below is not what the device is recording, but the video of a different device that started a live broadcast. It is that video that I would assume would be full screen given that I joined the channel as and Audience role. Also, if I am missing something somewhere, please let me know. Everything I've tried so far has the same result, so I'm reaching out :).

**To Reproduce**
1. On device 1, join a channel with `AgoraChannelData(clientRole: ClientRole.Broadcaster, channelProfile: ChannelProfile.LiveBroadcasting)`
2. On device 2, join the same channel, but with `AgoraChannelData(clientRole: ClientRole.Audience, channelProfile: ChannelProfile.LiveBroadcasting)`
3. Notice on device 2 that the screen splits and shows a blank top half (the place where its own local recording would go if it was publishing), and the live broadcast on the bottom.
4. If device 2 is android, notice that it turns on the microphone as indicated in the system tray at the top by a green dot.

**Expected behavior**
I would expect a full screen view of the live broadcast, and that it doesn't turn on my device's microphone.

**Screenshots**
<img width="434" alt="Screen Shot 2022-07-28 at 5 15 10 PM" src="https://user-images.githubusercontent.com/3729631/181652806-17885645-79ed-4f1d-84b0-280fd53b8761.png">

**Device:**
 - Device 1: iPhone 12 Pro - iOS 15.5
 - Device 2: Android Emulator - Pixel 3a - API 32, Android 12 - arm64-v8a
 - Flutter Version: 3.0.5
 - Dart Version: 2.17.6
 - agora_uikit: "1.0.2"

**Additional context**
Please forgive me if I'm missing something simple. I could be misunderstanding how to use the SDK/UI Kit or agora in generalj.

**Comment by Meherdeep** [comment]
@JoshJuncker This has been fixed with the new release v1.0.3 Let us know if it solves your issue.

**Comment by Meherdeep** [comment]
Closing this issue for now, if you are still facing the issue feel free to reopen it.
